// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkDQZ9bHHNQHfhwiCz8EGEPrDdx_PrAwY',
    appId: '1:128025602854:android:9e5c47edb6d05cc34c2fe7',
    messagingSenderId: '128025602854',
    projectId: 'verdeperto-19cb2',
    storageBucket: 'verdeperto-19cb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75Ix3C1d3PUNHSAjVQP8n4WcwZBurUAM',
    appId: '1:128025602854:ios:47e59c2983b9754c4c2fe7',
    messagingSenderId: '128025602854',
    projectId: 'verdeperto-19cb2',
    storageBucket: 'verdeperto-19cb2.appspot.com',
    iosClientId: '128025602854-tgkbqpn61un1pkjv4mrvgksojcq4n6cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
